using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using NextTask.Data;

namespace NextTask
{
    public partial class NewProject : Form
    {
        TaskService _taskService = TaskService.Instance();

        public NewProject()
        {
            InitializeComponent();
        }

        protected override void OnFormClosed(FormClosedEventArgs e)
        {
            this.Owner.Enabled = true;
            base.OnFormClosed(e);
        }

        private void addProject_Click(object sender, EventArgs e)
        {
            if (projectName.Text.Trim() != "")
            {
                var p = new Project();
                p.name = projectName.Text.Trim();
                
                //[FIX] projectid should be generated by the db.
                Random r = new Random(DateTime.Now.Millisecond + DateTime.Now.Second);
                p.projectId = r.Next();

                _taskService._projects.Add(p);

                projectName.Text = "";
            }
        }
    }
}
